---

- name: set DNS servers
  lineinfile:
    line: 'nameserver {{ item }}'
    dest: /etc/resolv.conf
  with_items: '{{ freeipa_client_dns_server }}'
  when:
    - freeipa_client_dns_server is defined
    - freeipa_client_dns_server != ''


- block:

    - name: enable mkhomedir
      lineinfile:
        dest: /etc/pam.d/common-session
        line: 'session     required      pam_mkhomedir.so skel=/etc/skel umask=0022'

    - name: enable sssd sudo functionality
      notify:
        - restart sssd
        - restart ssh
      lineinfile:
        dest: /etc/sssd/sssd.conf
        regexp: '^services.*'
        line: 'services = nss, pam, ssh, sudo'

  when: ansible_os_family == 'Debian'
