---

- name: install FreeIPA client
  package:
    name: '{{ freeipa_client_packages }}'
    update_cache: "{{ omit if ((ansible_pkg_mgr == 'dnf') and (ansible_version is version('2.7', '<'))) else 'yes' }}"
  delay: 10
  retries: 3
  register: result
  until: result is succeeded
